
/* This file was generated automatically by Zephir do not modify it! */

#ifndef ZEPHIR_CLASS_ENTRIES_H
#define ZEPHIR_CLASS_ENTRIES_H

#include "vof/cache/backendinterface.zep.h"
#include "vof/cache/backend.zep.h"
#include "vof/cache/frontendinterface.zep.h"
#include "vof/logger/adapterinterface.zep.h"
#include "vof/logger/formatterinterface.zep.h"
#include "vof/session/adapterinterface.zep.h"
#include "vof/logger/adapter.zep.h"
#include "vof/logger/formatter.zep.h"
#include "vof/session/adapter.zep.h"
#include "vof/cache/frontend/data.zep.h"
#include "vof/cache/backend/apc.zep.h"
#include "vof/cache/backend/apcu.zep.h"
#include "vof/cache/backend/file.zep.h"
#include "vof/cache/backend/libmemcached.zep.h"
#include "vof/cache/backend/memcache.zep.h"
#include "vof/cache/backend/memory.zep.h"
#include "vof/cache/backend/mongo.zep.h"
#include "vof/cache/backend/redis.zep.h"
#include "vof/cache/backend/xcache.zep.h"
#include "vof/cache/exception.zep.h"
#include "vof/cache/frontend/base64.zep.h"
#include "vof/cache/frontend/igbinary.zep.h"
#include "vof/cache/frontend/json.zep.h"
#include "vof/cache/frontend/msgpack.zep.h"
#include "vof/cache/frontend/none.zep.h"
#include "vof/cache/frontend/output.zep.h"
#include "vof/logger.zep.h"
#include "vof/logger/adapter/file.zep.h"
#include "vof/logger/adapter/firephp.zep.h"
#include "vof/logger/adapter/stream.zep.h"
#include "vof/logger/adapter/syslog.zep.h"
#include "vof/logger/exception.zep.h"
#include "vof/logger/formatter/firephp.zep.h"
#include "vof/logger/formatter/json.zep.h"
#include "vof/logger/formatter/line.zep.h"
#include "vof/logger/formatter/syslog.zep.h"
#include "vof/medoo.zep.h"
#include "vof/security/exception.zep.h"
#include "vof/security/random.zep.h"
#include "vof/session/adapter/files.zep.h"
#include "vof/session/adapter/libmemcached.zep.h"
#include "vof/session/adapter/memcache.zep.h"
#include "vof/session/adapter/redis.zep.h"
#include "vof/session/exception.zep.h"

#endif